info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  instance:
    #hostname: zuul-registry.testgitlab.svc
  ignoredServices: "*"
  routes:
    bdmbiometricosorquest:
      path: /bdmbiometricosorquest/**
      serviceId: bdmbiometricosorquest
    bdmbiometricosdummy:
      path: /bdmbiometricosdummy/**
      serviceId: bdmbiometricosdummy
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka.microserviciodemo.svc:8761/eureka/
      #defaultZone: http://eureka-registry.testgitlab.svc:8761/eureka/

hystrix:
  threadpool:
    default:
      coreSize: 1000
      maximumSize: 10000
      queueSizeRejectionThreshold: -1
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
              timeoutInMilliseconds: 41000
ribbon: 
     ConnectTimeout: 3000
     ReadTimeout: 60000