server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    #hostname: eureka.microserviciodemo.svc
    #hostname: eureka-registry.testgitlab.svc
    
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/