server:
  port: 8080

eureka:
  instance:
  client:
    serviceUrl:
      #defaultZone: http://eureka.microserviciodemo.svc:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 5
stores:
  ribbon:
    ServerListRefreshInterval: 1000

logging:
  level:
    se.callista: INFO
